apiVersion: v2
name: observer
version: 0.1.0
appVersion: "1.16.0"
description: kube-prometheus-stack, thanos for Central observer cluster
type: application
keywords: ["devops", "observability", "thanos", "infra"]
home: https://github.com/hyunkoes/monitroing
sources: ["https://github.com/hyunkoes/monitoring"]
maintainers:
  - name: hyunkoes hyunseok.Choi
    email: chs29359685@gmail.com
dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 26.1.0
    condition: kube-prometheus-stack.enabled
  - name: thanos
    repository: https://charts.bitnami.com/bitnami
    version: 11.4.0
    condition: thanos.enabled
